apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alerta
  template:
    metadata:
      labels:
        app: alerta

    spec:
      containers:
      - name: alerta-web
        image: alerta/alerta-web
        ports:
        - containerPort: 8080
        env:
          - name: DATABASE_URL
            value: 'mongodb://mongodb:27017/monitoring'
          - name: ADMIN_USERS
            value: 'admin@alerta.loc'
          - name: ADMIN_PASSWORD
            value: 'doberman'

      - name: mongodb
        image: mongo:4.0.19-xenial
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: mongodb-pv-storage
            mountPath: /data/db

      volumes:
        - name: mongodb-pv-storage
          hostPath:
            path: /storage/mongodb
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: alerta-nodeport
  labels:
    name: alerta-web
spec:
  type: NodePort
  selector:
    app: alerta
  ports:
    - nodePort: 30080
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  selector:
    app: alerta
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
